### ISSUE TITLE
AMD patch questions

### ISSUE THREAD

**Issue by joevt** [kingo132/a51m-r2-5700m-hackintosh#3]
Regarding [fix_navi10_4k_120hz.md](https://github.com/kingo132/a51m-r2-5700m-hackintosh/blob/39d2f5b73cf8c3a57ce65ce5afc134f54b51f5b8/fix_navi10_4k_120hz.md) :

Did you try an EDID override created by SwitchResX to see if the panel supports a slightly lower refresh rate, such as 117 Hz CVT-RB2, without Lilu & WhateverGreen?

Is the EDID different between the B173HAN04.4 and the B173ZAN06.1 panels? You only show one EDID and it doesn't show a 4K 120Hz mode. Please use [edid-decode](https://git.linuxtv.org/edid-decode.git/about/) to get all the info.
`edid-decode -cC theedid.bin > theedid.txt`

Does this enable DSC? Probably not since 4K120 is doable without DSC but only at 8 bpc for RGB or 4:4:4. Use the AGDCDiagnose command to find out what is being output to the display (resolution, timing, pixel format, DSC, link width, link rate, etc.) and to find out if it supports DSC.
```bash
/System/Library/Extensions/AppleGraphicsControl.kext/Contents/MacOS/AGDCDiagnose -a > AGDCDiagnose_B173ZAN06.1.txt 2>&1
```

The AGDCDiagnose output also includes the EDID.

**Comment by kingo132** [comment]
hi, @joevt this is the edid file of  B173HAN04.4 
[EDID.B173HAN04.4 .bin.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/7320836/EDID.B173HAN04.4.bin.zip)
And this is its edid decode result
```
edid-decode (hex):

00 ff ff ff ff ff ff 00 06 af 9d 44 00 00 00 00
11 1d 01 04 a5 26 16 78 03 c4 05 a5 55 4d 98 25
13 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01
01 01 01 01 01 01 ce 8f 80 b6 70 38 88 40 30 20
a5 00 7e d7 10 00 00 1a 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 1a 00 00 00 fe 00 35
59 4b 54 4a 80 42 31 37 33 48 41 4e 00 00 00 00
00 02 41 0d 9e 00 11 00 00 0b 01 0a 20 20 00 be

----------------

Block 0, Base EDID:
  EDID Structure Version & Revision: 1.4
  Vendor & Product Identification:
    Manufacturer: AUO
    Model: 17565
    Made in: week 17 of 2019
  Basic Display Parameters & Features:
    Digital display
    Bits per primary color channel: 8
    DisplayPort interface
    Maximum image size: 38 cm x 22 cm
    Gamma: 2.20
    Supported color formats: RGB 4:4:4
    First detailed timing includes the native pixel format and preferred refresh rate
    Display is continuous frequency
  Color Characteristics:
    Red  : 0.6474, 0.3320
    Green: 0.3017, 0.5937
    Blue : 0.1445, 0.0742
    White: 0.3134, 0.3291
  Established Timings I & II: none
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:  1920x1080  144.027931 Hz  16:9    175.138 kHz    368.140000 MHz (382 mm x 215 mm)
                 Hfront   48 Hsync  32 Hback  102 Hpol P
                 Vfront   10 Vsync   5 Vback  121 Vpol N
    Manufacturer-Specified Display Descriptor (0x00): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1a '................'
    Alphanumeric Data String: '5YKTJ'
    Manufacturer-Specified Display Descriptor (0x00): 00 00 00 02 41 0d 9e 00 11 00 00 0b 01 0a 20 20 '....A.........  '
Checksum: 0xbe
```
And this is the edid file of B173ZAN06.1 and its decode resultt
[EDID.B173ZAN06.1.bin.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/7320838/EDID.B173ZAN06.1.bin.zip)
```
edid-decode (hex):

00 ff ff ff ff ff ff 00 06 af 95 de 00 00 00 00
2d 1e 01 04 a5 26 15 78 03 0f 95 ae 52 43 b0 26
0f 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01
01 01 01 01 01 01 c4 d1 00 50 f0 70 7a 80 30 20
35 00 7d d6 10 00 00 18 00 00 00 fd 0c 30 78 13
13 6b 01 0a 20 20 20 20 20 20 00 00 00 fe 00 41
55 4f 0a 20 20 20 20 20 20 20 20 20 00 00 00 fe
00 42 31 37 33 5a 41 4e 30 36 2e 31 20 0a 01 a6

70 13 79 00 00 03 01 14 60 a3 01 84 ff 0e 4f 00
2f 00 1f 00 6f 08 79 00 02 00 04 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 34 90

----------------

Block 0, Base EDID:
  EDID Structure Version & Revision: 1.4
  Vendor & Product Identification:
    Manufacturer: AUO
    Model: 56981
    Made in: week 45 of 2020
  Basic Display Parameters & Features:
    Digital display
    Bits per primary color channel: 8
    DisplayPort interface
    Maximum image size: 38 cm x 21 cm
    Gamma: 2.20
    Supported color formats: RGB 4:4:4
    First detailed timing includes the native pixel format and preferred refresh rate
    Display is continuous frequency
  Color Characteristics:
    Red  : 0.6796, 0.3203
    Green: 0.2646, 0.6904
    Blue : 0.1503, 0.0595
    White: 0.3134, 0.3291
  Established Timings I & II: none
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:  3840x2160   60.030585 Hz  16:9    136.990 kHz    537.000000 MHz (381 mm x 214 mm)
                 Hfront   48 Hsync  32 Hback    0 Hpol N
                 Vfront    3 Vsync   5 Vback  114 Vpol N
    Display Range Limits:
      Monitor ranges (Bare Limits): 48-120 Hz V, 274-274 kHz H, max dotclock 1070 MHz
    Alphanumeric Data String: 'AUO'
    Alphanumeric Data String: 'B173ZAN06.1 '
  Extension blocks: 1
Checksum: 0xa6

----------------

Block 1, DisplayID Extension Block:
  Version: 1.3
  Extension Count: 0
  Display Product Type: Extension Section
  Video Timing Modes Type 1 - Detailed Timings Data Block:
    DTD:  3840x2160  120.017573 Hz  16:9    273.880 kHz   1073.610000 MHz (aspect 16:9, no 3D stereo, preferred)
               Hfront   48 Hsync  32 Hback    0 Hpol N
               Vfront    3 Vsync   5 Vback  114 Vpol N
  Checksum: 0x34
Checksum: 0x90
```

And this is the result of your AGDCDiagnose_B173ZAN06.1.txt
[AGDCDiagnose_B173ZAN06.1.txt](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/7320854/AGDCDiagnose_B173ZAN06.1.txt)

**Comment by kingo132** [comment]
Hi, @joevt, thanks for your information. I think I made SwitchResX work with 4k@120hz without the patch.
The parameter is set below.
![image](https://user-images.githubusercontent.com/46492291/136760653-77f4d4c5-b3a0-4962-849e-2b62a8e0f7c2.png)

The most important thing is it must be CVT-RB v2 that can run 4k@120hz, without v2 it won't take effect.
![image](https://user-images.githubusercontent.com/46492291/136760819-b2e7c4de-1fc9-4fe4-976e-b1a43e6028c2.png)
![image](https://user-images.githubusercontent.com/46492291/136760838-5df12c7a-0669-4cb4-8e88-a8ae02aa25f3.png)

The screen is actually 120hz now without patch but a SwitchResX configuration.

**Comment by joevt** [comment]
> The screen is actually 120hz now without patch but a SwitchResX configuration.

That makes sense since the patch only increases allowed bandwidth by 3% (the amount reserved for FEC even though your display doesn't require FEC).

Without the patch, you need to reduce the bandwidth by specifying a lower pixel clock. The max pixel clock is 1047.6 MHz (3% less than the 1080 MHz allowed by HBR3 link rate to account for FEC overhead).

The AGDCDiagnose output will tell you if your display supports FEC.

4K120 using CVT-RB2 is 1075MHz. I see you disabled CVT-RB2 and reduced the vertical front porch from 113 to 40.
You could try 1047.6MHz with vertical front porch set to 111.
Or 1047.59MHz if that doesn't work.

**Comment by kingo132** [comment]
> > The screen is actually 120hz now without patch but a SwitchResX configuration.
> 
> That makes sense since the patch only increases allowed bandwidth by 3% (the amount reserved for FEC even though your display doesn't require FEC).
> 
> Without the patch, you need to reduce the bandwidth by specifying a lower pixel clock. The max pixel clock is 1047.6 MHz (3% less than the 1080 MHz allowed by HBR3 link rate to account for FEC overhead).
> 
> The AGDCDiagnose output will tell you if your display supports FEC.
> 
> 4K120 using CVT-RB2 is 1075MHz. I see you disabled CVT-RB2 and reduced the vertical front porch from 113 to 40. You could try 1047.6MHz with vertical front porch set to 111. Or 1047.59MHz if that doesn't work.

I didn't reduce any value, they are set automatically after I select CVT-RB v2.

**Comment by joevt** [comment]
> I didn't reduce any value, they are set automatically after I select CVT-RB v2.

Your screenshot shows "Use simplified settings" is not selected. CVT-RB2 is not being used if that is not selected.

When I enable CVT-RB2 and enter 3840x2160 120Hz, I get a pixel clock of 1075.81 MHz.
