### ISSUE TITLE
120hz patch no longer functions on Monterey 12.4

### ISSUE THREAD

**Issue by FabianPonce** [kingo132/a51m-r2-5700m-hackintosh#4]
I'm not sure if this repo is still maintained but this is the most detailed source of information I've found regarding the bandwidth limitations for high-refresh rate monitors. 

I tried to rebuild the patch by working my way through the symbols and I've found `__ZN35AMDRadeonX6000_AmdRadeonFramebuffer39validateDirtyDisplayPathTimingBandwidthERh`, but I can't seem to find anything that would relate to the bandwidth in kbps. 

I did try to wrap this function in WEG myself and have it return `kIOReturnSuccess`, but that just made my system not boot. 

I'm still digging into this and the other AMD kexts but I thought you might know more. :-)

**Comment by kingo132** [comment]
Sorry, I'm preparing my exam recently so I have no time to handle this. Perhaps I will look into it 2 or 3 months later.

**Comment by kingo132** [comment]
Hi, I suppose you can use tool SwitchResX to get 120hz working without any WEG patches. Try using my custom resolution configuration in SwitchResX. I'm currently running Monterey with 120hz working without any patches.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/46492291/177187546-3adc9491-4955-4a20-86c3-90584746e0f9.png">
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/46492291/177187637-bface51a-3117-4cd1-b5eb-d64ff08ddd76.png">
Meanwhile, if you want to go the patch way. You can try to see the panic log to figure out why your code does not work.
And Monterey has removed the function symbol in AMDRadeonX6000Framebuffer.kext. So you have to call some C-style functions by address. See https://github.com/acidanthera/WhateverGreen/pull/90#issuecomment-1173372092 for more detail.

**Comment by wander555** [comment]
> Hi, I suppose you can use tool SwitchResX to get 120hz working without any WEG patches. Try using my custom resolution configuration in SwitchResX. I'm currently running Monterey with 120hz working without any patches. <img alt="image" width="532" src="https://user-images.githubusercontent.com/46492291/177187546-3adc9491-4955-4a20-86c3-90584746e0f9.png"> <img alt="image" width="1281" src="https://user-images.githubusercontent.com/46492291/177187637-bface51a-3117-4cd1-b5eb-d64ff08ddd76.png"> Meanwhile, if you want to go the patch way. You can try to see the panic log to figure out why your code does not work. And Monterey has removed the function symbol in AMDRadeonX6000Framebuffer.kext. So you have to call some C-style functions by address. See [acidanthera/WhateverGreen#90 (comment)](https://github.com/acidanthera/WhateverGreen/pull/90#issuecomment-1173372092) for more detail.

Hi，I used your setting in swx,but my screen turn black....
DId U use the DP 1.4 or the HDMI?Any other settings ？

**Comment by kingo132** [comment]
> 

Yes, I use this configuration for my Alienware laptop which uses eDP connected the graphic card to the internal 4k 120hz screen. But I don't know the exact version of this DP connection.
