### ISSUE TITLE
Thunderbolt issues

### ISSUE THREAD

**Issue by Larry2244** [kingo132/a51m-r2-5700m-hackintosh#5]
Thunderbolt only showed in PCI devices. "No drivers are loaded" is still displayed in the Thunderbolt/USB4 devices list, but the thunderbolt 3 device has actually worked.  I have searched in Tonymacx86 and find a way to deal with this problem to deal with it by flashing a iMac thunderbolt firmware. Did u try this?

**Comment by kingo132** [comment]
I don't believe it is worth doing. The only benefit of flashing the firmware is to have the correct information displayed in the system report. It does not affect the actual function of Thunderbolt.

**Comment by Larry2244** [comment]
Sorry, this is a mistake of mine. I used to think that my egpu didn't work properly because of the firmware problem of thunderbolt 3, but in fact, it wasn't. My egpu graphics card was broken. By the way, I found there‘s an external graphics port to connect an Alienware Graphics Amplifier behind the laptop. Is there a way to make it work? And although the brightness of my built-in display can be adjusted after using your WhateverGreen.kext , it is still very dark at the maximum brightness.

**Comment by kingo132** [comment]
First of all, how dark is the maximum brightness compared to what it is under Windows? In my a51m, the maximum brightness of Mac OS is the same as Windows.
Second, I haven't tried that Alienware eGPU port in Mac OS. I guess it should work in Mac because it may be just a direct PCI connection like Thunderbolt.

**Comment by Larry2244** [comment]
For the Alienware eGPU ports, I just bought one online, and I believe it will be sent to my house soon.As you said, It looks like a PCIe direct channel. I hope it works normally. After having a try, I will share my results with you.

For the screen, It’s really dark, looks like only 1/3 of its maximum brightness under windows. I currently fixed it by using a third party monitor control software and the original Whatevergreen.Kext.It works fine now.

From  iPhone

在 2022年7月13日，下午10:21，kingo ***@***.***> 写道：

﻿

First of all, how dark is the maximum brightness compared to what it is under Windows? In my a51m, the maximum brightness of Mac OS is the same as Windows.
Second, I haven't tried that Alienware eGPU port in Mac OS. I guess it should work in Mac because it may be just a direct PCI connection like Thunderbolt.

**Comment by kingo132** [comment]
Please tell me:
1. the exact Mac OS version number you are using, eg 11.5.3
2. please attach this file here to me: /System/Library/Extensions/AMDRadeonX6000Framebuffer.kext/Contents/MacOS/AMDRadeonX6000Framebuffer
3. which of my modified Whatevergreen.kext are you using? Is it the newest version which I updated several days ago?
4. I guess you are using the wrong SSDT-PNLF.aml, please attach this file of yours here to me.
5. It would be better if you could send me a dump of IOReg using the tool IORegistryExplorer.

**Comment by Larry2244** [comment]
Thank you so much for your help, here is my situation.

1. Version 12.4(21F79)
2. in my Archive.zip
3. yes, the latest one
4&5. in my Archive.zip
[Archive.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/9103677/Archive.zip)
I

**Comment by kingo132** [comment]
I suppose you could try to modify your SSDT-PNLF.aml and change UID from Zero to 0x13.
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/46492291/178781041-46c7a2fb-c850-465d-aaf3-b387dd5d29c7.png">
Or just use my SSDT-PNLF.aml
[SSDT-PNLF.aml.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/9104064/SSDT-PNLF.aml.zip)

**Comment by Larry2244** [comment]
Thank U so much, My friend! I have edited my PNLF, and everything works fine under your whatevergreen.kext now!
