### ISSUE TITLE
Almost got the trackpad working.

### ISSUE THREAD

**Issue by TechProgenitor** [kingo132/a51m-r2-5700m-hackintosh#6]
Hi Kingo, long time no speak,
I noticed that you’ve been active lately, and wanted to let you know that I’ve just about gotten the trackpad working properly for our laptop. Everything works including gestures, however the latency/polling rate for the trackpad is terrible.

You have to use VoodooPS2Controller.kext, VoodooInput.kext, and VoodooPS2Trackpad.kext:
![Screen Shot 2022-07-14 at 1 28 36 PM](https://user-images.githubusercontent.com/89800154/179078518-64cd4e6d-6ff0-4c76-bbb3-29304065bb66.png)

Today I figured out how to get the trackpad buttons working with these three kexts:
You have to edit the info.plist file of VoodooPS2Trackpad.kext, and add “Thinkpad = True” to the default section for Synaptics TouchPad.
![Screen Shot 2022-07-14 at 1 26 01 PM](https://user-images.githubusercontent.com/89800154/179078741-c6196b46-4579-4960-8957-69ecfd415867.png)

I was hoping that you might have an idea on how to increase the polling rate.
(PS, great job fixing sleep/wake! It’s working for me too albeit the black screen after a really long sleep.)

**Comment by TechProgenitor** [comment]
KINGO!!! I FIGURED IT OUT!!!!
Replace VoodooI2CHID.kext with VoodooRMI.kext and RMII2C.kext!
There's zero latency and the trackpad gestures work beautifully now!!!

This is a very interesting trackpad! It supports both the I2C and PS2 protocols…
I figured out how to change the PS2 polling rate for the VoodooPS2 kexts, but the driver in general runs super laggy on this computer. You have to change the polling rate within the config.plist file itself.
The parameters that you have to modify are PointerPollMin and PointerPollMax.
The pointer on the boot loader splash screen seems to run through PS2, so these config.plist settings will affect it, but it doesn't appear to have the lag that VoodooPS2 has.

Now the laptop feels like an actual MacBook!
Everything at this point I’d say is just small optimizations to make the computer perform better.
(PS, the black screen fix is working for me too! Great job!)

**Comment by kingo132** [comment]
The trackpad gesture works perfectly now by following your instructions. It's really great to have you participate in this project.
