### ISSUE TITLE
graphical glitching fix using new open core 0.8.4

### ISSUE THREAD

**Issue by sephoriths** [kingo132/a51m-r2-5700m-hackintosh#9]
Hi, touchpad still some laggy when move the mouse, can you make a fix on this, many thanks to you!

**Comment by TechProgenitor** [comment]
Hi sephoriths, I'm assuming that you're talking about the OpenCanopy boot picker?
Within the OS itself, the trackpad seems to work perfectly.

The trackpad if I’m right is driven by PS2 instead of I2C on the OpenCanopy menu (this trackpad supports both protocols), and the controls for the PS2 performance are in the config.plist.
Go to the AppleInput tab in the config file and play with the PointerPollMin and PointerPollMax values.

I haven’t played with the trackpad much here because adjusting it makes my display lag more (I’ve enabled DirectGOPRendering in my config.plist to remove glitching at the cost of rendering speed). I’m curious though how adjusting these values affect Kingo as it sounds like her display doesn’t need the DirectGOPRendering option.

I wish OpenCore allowed you to inject an EDID or use the I2C driver (VoodooRMI) within OpenCanopy's boot picker.

**Comment by sephoriths** [comment]
Hi TechProgenitor, thanks for your reply, can you please upload your EFI? My touchpad seems not working smoothly within the os itself. I am using  144hz screen, how about you ? I think we've met the same problem under OpenCanopy boot picker, graphical glitching still happens without enable DirectGOPRendering option.

**Comment by sephoriths** [comment]
> Hi sephoriths, I'm assuming that you're talking about the OpenCanopy boot picker? Within the OS itself, the trackpad seems to work perfectly.
> 
> The trackpad if I’m right is driven by PS2 instead of I2C on the OpenCanopy menu (this trackpad supports both protocols), and the controls for the PS2 performance are in the config.plist. Go to the AppleInput tab in the config file and play with the PointerPollMin and PointerPollMax values.
> 
> I haven’t played with the trackpad much here because adjusting it makes my display lag more (I’ve enabled DirectGOPRendering in my config.plist to remove glitching at the cost of rendering speed). I’m curious though how adjusting these values affect Kingo as it sounds like her display doesn’t need the DirectGOPRendering option.
> 
> I wish OpenCore allowed you to inject an EDID or use the I2C driver (VoodooRMI) within OpenCanopy's boot picker.

Another idea I think is that may be we can find a way to disable cursor when using boot picker? Keyboard is enough, just let the cursor go away. BTW, within the os itself, the trackpad seems still not work perfectly, i feel laggy ..... may I use your newest efi have a try? Many thanks!

**Comment by TechProgenitor** [comment]
Oh, in that case I wildly misinterpreted this.
(Didn't realize that 0.8.4 was a very new version lol.)
I'll take a look at 0.8.4 (I'm currently running 0.8.3), but my guess is that you could be using VoodooPS2 (which was super laggy on my system) instead of VoodooI2C/VoodooRMI.
Other than that, yea, I've got the stock 1080p 144HZ screen, and it's a pain with OpenCanopy.
To disable the cursor set PointerSupport to "False" within your config.plist.

**Comment by sephoriths** [comment]
> Oh, in that case I wildly misinterpreted this.
> (Didn't realize that 0.8.4 was a very new version lol.)
> I'll take a look at 0.8.4 (I'm currently running 0.8.3), but my guess is that you could be using VoodooPS2 (which was super laggy on my system) instead of VoodooI2C/VoodooRMI.
> Other than that, yea, I've got the stock 1080p 144HZ screen, and it's a pain with OpenCanopy.
> To disable the cursor set PointerSupport to "False" within your config.plist.

Can you please send me the EFI with zip format ? I am not familiar with this ... Thank you !
sephorith.vip@gmail.com

**Comment by TechProgenitor** [comment]
Hi sephoriths, I'm wrong,
Instead of setting PointerSupport to "False", you set PickerAttributes to "0" to remove the bootpicker pointer.
Looking at the OC releases, 0.8.4 hasn't exactly been officially released yet (though it'll probably come out very very soon).
For the sake of stability, I'd personally rather wait it out a few days before making a full 0.8.4 EFI for you (unless Kingo beats me to it).

**Comment by sephoriths** [comment]
> Hi sephoriths, I'm wrong, Instead of setting PointerSupport to "False", you set PickerAttributes to "0" to remove the bootpicker pointer. Looking at the OC releases, 0.8.4 hasn't exactly been officially released yet (though it'll probably come out very very soon). For the sake of stability, I'd personally rather wait it out a few days before making a full 0.8.4 EFI for you (unless Kingo beats me to it).

Okay, glad to hear that! i will follow your suggestion and have a try first, can you attach a pic about your current opencore configuration? i think the driver order of mine is incorrect.

**Comment by sephoriths** [comment]
> Hi sephoriths, I'm wrong, Instead of setting PointerSupport to "False", you set PickerAttributes to "0" to remove the bootpicker pointer. Looking at the OC releases, 0.8.4 hasn't exactly been officially released yet (though it'll probably come out very very soon). For the sake of stability, I'd personally rather wait it out a few days before making a full 0.8.4 EFI for you (unless Kingo beats me to it).

Maybe attach config.plist file to me is enough, let me see the difference ... so i can make a study on it

**Comment by sephoriths** [comment]
I think the newest master branch version of the project, cannot make touchpad working, have you try it or it's my personal problem?

**Comment by TechProgenitor** [comment]
Hi sephoriths,
I've attached a screenshot of exactly what you need in your config.plist to get the trackpad to work:

![Trackpad Kext Order](https://user-images.githubusercontent.com/89800154/188125622-8dda72ca-2fc8-453f-b0f3-d18800deca8c.jpg)


Make sure that you disable/delete any kext that has "VoodooPS2" in its name.

**Comment by sephoriths** [comment]
> Hi sephoriths, I've attached a screenshot of exactly what you need in your config.plist to get the trackpad to work:
> 
> ![Trackpad Kext Order](https://user-images.githubusercontent.com/89800154/188125622-8dda72ca-2fc8-453f-b0f3-d18800deca8c.jpg)
> 
> Make sure that you disable/delete any kext that has "VoodooPS2" in its name.

Hi, TechProgenitor
I follow your suggestion, and remove all VoodooPS2 kext and follow the order in the pic.

![pic](https://user-images.githubusercontent.com/112638433/188132809-2047840f-3c4a-4f03-8dfa-c649807fcb71.png)

Still no luck, touchpad not working ...

**Comment by sephoriths** [comment]
![111](https://user-images.githubusercontent.com/112638433/188133566-b037729e-1bee-4a19-8a28-ba63d96fa4fa.png)

**Comment by sephoriths** [comment]
Only these three kext related to touchpad is used, I removed all other VoodooPS2 kext in the kexts directory

![666](https://user-images.githubusercontent.com/112638433/188137545-ebc72cf0-6dc6-40db-8091-739896b7b59c.png)

**Comment by sephoriths** [comment]
and use the original kext, still not working, so I am so confused now ...
![2222](https://user-images.githubusercontent.com/112638433/188140439-514405d1-2442-4ec3-9387-9616fa4dba05.png)

**Comment by sephoriths** [comment]
> Hi sephoriths, I'm wrong,
> Instead of setting PointerSupport to "False", you set PickerAttributes to "0" to remove the bootpicker pointer.
> Looking at the OC releases, 0.8.4 hasn't exactly been officially released yet (though it'll probably come out very very soon).
> For the sake of stability, I'd personally rather wait it out a few days before making a full 0.8.4 EFI for you (unless Kingo beats me to it).

whoops, I think I can't make it working but only PS2 way .... I promise if you can share your EFI with me, just for personal use

**Comment by sephoriths** [comment]
need patch? my i2c bios device name value is : \_SB.PCI0.I2C0.I2CD

**Comment by sephoriths** [comment]
> Hi sephoriths, I've attached a screenshot of exactly what you need in your config.plist to get the trackpad to work:
> 
> ![Trackpad Kext Order](https://user-images.githubusercontent.com/89800154/188125622-8dda72ca-2fc8-453f-b0f3-d18800deca8c.jpg)
> 
> Make sure that you disable/delete any kext that has "VoodooPS2" in its name.

Hi TechProgenitor:

need your help, I have done exactly the same thing as you do, but touchpad still not working

I can only drive the PS2 mode, but so laggy

![000](https://user-images.githubusercontent.com/112638433/188254928-c4179aab-5caf-48ab-8c3d-a63e1528760f.png)

**Comment by TechProgenitor** [comment]
Hi sephoriths,
Sorry to see that you’ve having this much trouble, but it’s really odd that you’re having these issues. How similar is your EFI to Kingos because hers for OC 0.8.3 works perfectly on my computer.

I’d rather wait for the official 0.8.4 release to build you a newer EFI, but I’m willing to take a look at your current one in the meantime to see if I can get it to work. Perhaps you could share your current config.plist over here, and I could tinker with it on my end?

**Comment by sephoriths** [comment]
Hi TechProgenitor:

The zipped file is my EFI, the trackpad is working but not as smoothly as it was under windows.
I can feel trackpad very smoothly under windows, but for Mac I can feel lag.
[EFI.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/9482270/EFI.zip)

**Comment by sephoriths** [comment]
> Hi sephoriths, Sorry to see that you’ve having this much trouble, but it’s really odd that you’re having these issues. How similar is your EFI to Kingos because hers for OC 0.8.3 works perfectly on my computer.
> 
> I’d rather wait for the official 0.8.4 release to build you a newer EFI, but I’m willing to take a look at your current one in the meantime to see if I can get it to work. Perhaps you could share your current config.plist over here, and I could tinker with it on my end?

EFI uploaded to you, I enable the ps2 controller for trackpad because without this, the trackpad even will not working, now the problem is still the lag .. is your trackpad feel very smoothly like under windows? may be you can upload your 0.8.3 version to me have a try, the hardware is same as kinggo's hardware but monitor, my monitor is 144hz 1080p

**Comment by sephoriths** [comment]
> Hi sephoriths, Sorry to see that you’ve having this much trouble, but it’s really odd that you’re having these issues. How similar is your EFI to Kingos because hers for OC 0.8.3 works perfectly on my computer.
> 
> I’d rather wait for the official 0.8.4 release to build you a newer EFI, but I’m willing to take a look at your current one in the meantime to see if I can get it to work. Perhaps you could share your current config.plist over here, and I could tinker with it on my end?

Hi, I'am sorry, I made a mistake, please override my newest efi

[config.plist.zip](https://github.com/kingo132/a51m-r2-5700m-hackintosh/files/9482300/config.plist.zip)

**Comment by TechProgenitor** [comment]
Interestingly enough, my trackpad works perfectly without any issues under your EFI, and the most recent config.plist file that you've sent me...
What macOS version are you running? I'm able to use the trackpad perfectly on Big Sur and Monterey.
Perhaps your BIOS is the culprit? I’m personally running version 0.1.18.0

**Comment by sephoriths** [comment]
> Interestingly enough, my trackpad works perfectly without any issues under your EFI, and the most recent config.plist file that you've sent me...
> What macOS version are you running? I'm able to use the trackpad perfectly on Big Sur and Monterey.
> Perhaps your BIOS is the culprit? I’m personally running version 0.1.18.0

Bigsur 11.6.8, the zip file I send you is wrong .... get into system I think is impossible, which version you use? My bios is 0.1.18.0

**Comment by sephoriths** [comment]
> 

I know why, some kext files version may be different, can you upload your dev EFI to me ? I think its the fastest way to inspect the problem, My mail box is sephorith.vip@gmail.com, I will resetthe S/N number once I get your version.

**Comment by sephoriths** [comment]
I mean the plist file the last time I uploaded in the topic is correct. So make a conclusion now:

OS:Bigsur 11.6.8
BIOS: 1.18.0
HARDWARE: the same as Kingo's except the monitor

**Comment by TechProgenitor** [comment]
I used the exact EFI in your zip file and only replaced the config.plist file with the newest one.
(I couldn't enter my system with the original config file.)
There's absolutely nothing wrong with your EFI. It might be a difference in one of your [BIOS settings](https://github.com/kingo132/a51m-r2-5700m-hackintosh/issues/7#issuecomment-1194951588) or trackpad hardware.
Compare your BIOS settings at your own discretion (tip: disabling Firmware TPM fixes wake).
Could you send a video and/or an ioreg dump with your EFI and that config.plist?
It's really weird that this isn't working properly for you.

**Comment by TechProgenitor** [comment]
I used the exact EFI in your zip file and only replaced the config.plist file with the newest one.
(I couldn't enter my system with the original config file.)
There's absolutely nothing wrong with your EFI. It might be a difference in one of your [BIOS settings](https://github.com/kingo132/a51m-r2-5700m-hackintosh/issues/7#issuecomment-1194951588).
Compare your BIOS settings at your own discretion (tip: disabling Firmware TPM fixes wake).
Could you send a video and/or an ioreg dump with your EFI and that config.plist?
The only last resort I can think of would be a clean install.
It's really weird that this isn't working properly for you.

**Comment by sephoriths** [comment]
> I used the exact EFI in your zip file and only replaced the config.plist file with the newest one.
> (I couldn't enter my system with the original config file.)
> There's absolutely nothing wrong with your EFI. It might be a difference in one of your [BIOS settings](https://github.com/kingo132/a51m-r2-5700m-hackintosh/issues/7#issuecomment-1194951588).
> Compare your BIOS settings at your own discretion (tip: disabling Firmware TPM fixes wake).
> Could you send a video and/or an ioreg dump with your EFI and that config.plist?
> The only last resort I can think of would be a clean install.
> It's really weird that this isn't working properly for you.

waiting for your 0.8.4 EFI, ..... the bios setting is no problem

**Comment by sephoriths** [comment]
> TechProgenitor

how to remove the date info of EFI boot menu at bottom right corner?

**Comment by sephoriths** [comment]
> Interestingly enough, my trackpad works perfectly without any issues under your EFI, and the most recent config.plist file that you've sent me...
> What macOS version are you running? I'm able to use the trackpad perfectly on Big Sur and Monterey.
> Perhaps your BIOS is the culprit? I’m personally running version 0.1.18.0

Trackpad is too lag to use ........ I want your newest EFI now ..... so we can research the project together from now on

**Comment by sephoriths** [comment]
😂 can you please upload your efi in zip format to me ? i tried a lot, but
still fails,

TechProgenitor ***@***.***> 于2022年9月2日周五 19:00写道：
